version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - ./database/data/db:/data/db
