version: "3.8"
services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - /database/data:/data/db

  backend:
    build: ./backend
    container_name: backend-1
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    stdin_open: true
    tty: true